//Source code generated by AppGPT (www.appgpt.tech)
import { Admin, Resource, CustomRoutes } from 'react-admin';
import { customDataProvider } from './dataProvider';
import fakeDataProvider from 'ra-data-fakerest';
import { Dashboard } from './dashboard';
import { authProvider, apInitialize } from './authProvider';
import { i18nProvider } from './i18nProvider';
import LoginPage, { Login } from './Login';
import data from './data';
import {
  dailyAstrologyUpdatesList,
  dailyAstrologyUpdatesCreate,
  dailyAstrologyUpdatesEdit,
} from './resources/dailyAstrologyUpdates';
import {
  subscriptionPlansList,
  subscriptionPlansCreate,
  subscriptionPlansEdit,
} from './resources/subscriptionPlans';
import { usersList, usersCreate, usersEdit } from './resources/users';
import {
  paymentDetailsList,
  paymentDetailsCreate,
  paymentDetailsEdit,
} from './resources/paymentDetails';
import dailyAstrologyUpdatesIcon from '@mui/icons-material/Update';
import subscriptionPlansIcon from '@mui/icons-material/Subscriptions';
import usersIcon from '@mui/icons-material/People';
import paymentDetailsIcon from '@mui/icons-material/Payment';
// SUPERTOKENS
import React from 'react';
import SuperTokens, {
  SuperTokensWrapper,
  getSuperTokensRoutesForReactRouterDom,
} from 'supertokens-auth-react';
import ThirdPartyPasswordless from 'supertokens-auth-react/recipe/thirdpartypasswordless';
import Session from 'supertokens-auth-react/recipe/session';
import { BrowserRouter, Routes, Route, Link } from 'react-router-dom';
import * as reactRouterDom from 'react-router-dom';
let sessionFn = Session.init();
SuperTokens.init({
  appInfo: {
    appName: import.meta.env.VITE_SUPERTOKENS_APPNAME,
    apiDomain: import.meta.env.VITE_BACKEND_DOMAIN,
    websiteDomain: import.meta.env.VITE_SUPERTOKENS_WEBSITEDOMAIN,
    apiBasePath: import.meta.env.VITE_BACKEND_APIPATH + '/auth',
    websiteBasePath: import.meta.env.VITE_SUPERTOKENS_WEBSITEBASEPATH,
  },
  recipeList: [
    ThirdPartyPasswordless.init({
      contactMethod: 'EMAIL',
      signInUpFeature: {
        providers: [
          ThirdPartyPasswordless.Github.init(),
          //ThirdPartyPasswordless.Google.init(),
          //ThirdPartyPasswordless.Facebook.init(),
          //ThirdPartyPasswordless.Apple.init(),
        ],
      },
    }),
    sessionFn,
  ],
});
apInitialize(Session);
// END SUPERTOKENS
let dataProvider: any;
if (import.meta.env.VITE_USE_BACKEND_DATA === 'true') {
  dataProvider = customDataProvider(
    import.meta.env.VITE_BACKEND_DOMAIN +
      import.meta.env.VITE_BACKEND_APIPATH +
      '/proxy',
  );
} else {
  dataProvider = fakeDataProvider(data.defaultData);
}

const App = () => (
  <SuperTokensWrapper>
    <BrowserRouter basename="/ab95bfed9">
      <Admin
        authProvider={
          import.meta.env.VITE_ENVIRONMENT != 'DEV' ? authProvider : undefined
        }
        requireAuth
        loginPage={LoginPage}
        dataProvider={dataProvider}
        i18nProvider={i18nProvider}
        dashboard={Dashboard}
      >
        <Resource
          name="dailyAstrologyUpdates"
          options={{ label: 'Daily Astrology Updates' }}
          list={dailyAstrologyUpdatesList}
          create={dailyAstrologyUpdatesCreate}
          edit={dailyAstrologyUpdatesEdit}
          recordRepresentation="astrologySigns"
          icon={dailyAstrologyUpdatesIcon}
        />
        <Resource
          name="subscriptionPlans"
          options={{ label: 'Subscription Plans' }}
          list={subscriptionPlansList}
          create={subscriptionPlansCreate}
          edit={subscriptionPlansEdit}
          recordRepresentation="name"
          icon={subscriptionPlansIcon}
        />
        <Resource
          name="users"
          options={{ label: 'Users' }}
          list={usersList}
          create={usersCreate}
          edit={usersEdit}
          recordRepresentation="chat"
          icon={usersIcon}
        />
        <Resource
          name="paymentDetails"
          options={{ label: 'Payment Details' }}
          list={paymentDetailsList}
          create={paymentDetailsCreate}
          edit={paymentDetailsEdit}
          recordRepresentation="upiId"
          icon={paymentDetailsIcon}
        />
        <CustomRoutes noLayout>
          {/*This renders the login UI on the /auth route*/}
          {getSuperTokensRoutesForReactRouterDom(reactRouterDom)}
          {/*Your app routes*/}
        </CustomRoutes>
      </Admin>
    </BrowserRouter>
  </SuperTokensWrapper>
);

export default App;
