//Source code generated by AppGPT (www.appgpt.tech)
let data: any = {
  defaultData: {
    dailyAstrologyUpdates: [
      { astrologySigns: 'astrologySigns 1', id: 96 },
      { astrologySigns: 'astrologySigns 2', id: 0 },
      { astrologySigns: 'astrologySigns 3', id: 75 },
      { astrologySigns: 'astrologySigns 4', id: 60 },
      { astrologySigns: 'astrologySigns 5', id: 73 },
    ],
    subscriptionPlans: [
      { name: 'name 1', id: 59 },
      { name: 'name 2', id: 28 },
      { name: 'name 3', id: 59 },
      { name: 'name 4', id: 70 },
      { name: 'name 5', id: 70 },
    ],
    users: [
      { chat: 'chat 1', id: 29 },
      { chat: 'chat 2', id: 18 },
      { chat: 'chat 3', id: 6 },
      { chat: 'chat 4', id: 89 },
      { chat: 'chat 5', id: 57 },
    ],
    paymentDetails: [
      { upiId: 'upiId 1', id: 30 },
      { upiId: 'upiId 2', id: 6 },
      { upiId: 'upiId 3', id: 17 },
      { upiId: 'upiId 4', id: 12 },
      { upiId: 'upiId 5', id: 68 },
    ],
  },
};
export default data;
