//Source code generated by AppGPT (www.appgpt.tech)
import { mergeTranslations } from 'ra-core';
import polyglotI18nProvider from 'ra-i18n-polyglot';
import enOriginal from 'ra-language-english';
import frOriginal from 'ra-language-french';

const enResources = {
  resources: {
    dailyAstrologyUpdates: {
      name: 'Daily Astrology Updates',
      fields: { astrologySigns: 'Astrology Signs', id: 'id' },
    },
    subscriptionPlans: {
      name: 'Subscription Plans',
      fields: { name: 'Name', id: 'id' },
    },
    users: { name: 'Users', fields: { chat: 'Chat', id: 'id' } },
    paymentDetails: {
      name: 'Payment Details',
      fields: { upiId: 'Upi Id', id: 'id' },
    },
  },
};
const frResources = {
  resources: {
    dailyAstrologyUpdates: {
      name: 'Daily Astrology Updates (fr)',
      fields: { astrologySigns: 'Astrology Signs (fr)', id: 'id' },
    },
    subscriptionPlans: {
      name: 'Subscription Plans (fr)',
      fields: { name: 'Name (fr)', id: 'id' },
    },
    users: { name: 'Users (fr)', fields: { chat: 'Chat (fr)', id: 'id' } },
    paymentDetails: {
      name: 'Payment Details (fr)',
      fields: { upiId: 'Upi Id (fr)', id: 'id' },
    },
  },
};

const en = mergeTranslations(enOriginal, enResources);
const fr = mergeTranslations(frOriginal, frResources);

const translations = { en, fr };
export const i18nProvider = polyglotI18nProvider(
  (locale) => translations[locale],
  'en', //default locale
  [
    { locale: 'en', name: 'English' },
    { locale: 'fr', name: 'Français' },
  ],
);
